### ISSUE TITLE
Can you help me

### ISSUE THREAD

**Issue by Maro9898** [souravrs999/FaucetCryptoBot#1]
can you help me

**Comment by Maro9898** [comment]
Traceback (most recent call last):
  File "C:\Users\user\Desktop\FaucetCryptoBot\bot.py", line 1, in <module>
    from FaucetCryptoBot import FaucetCryptoBot
  File "C:\Users\user\Desktop\FaucetCryptoBot\FaucetCryptoBot\__init__.py", line 1, in <module>
    from .fcbot import FaucetCryptoBot
  File "C:\Users\user\Desktop\FaucetCryptoBot\FaucetCryptoBot\fcbot.py", line 19
    "browser", f"starting browser session: {self.driver.session_id}"
                                                                   ^
SyntaxError: invalid syntax
>>>

**Comment by Maro9898** [comment]
Traceback (most recent call last):[0m
[0m  File "C:\Users\user\Desktop\FaucetCryptoBot\bot.py", line 1, in <module>
    from FaucetCryptoBot import FaucetCryptoBot
[0m[0m  File "C:\Users\user\Desktop\FaucetCryptoBot\FaucetCryptoBot\__init__.py", line 1, in <module>
    from .fcbot import FaucetCryptoBot
[0m[0m  File "C:\Users\user\Desktop\FaucetCryptoBot\FaucetCryptoBot\fcbot.py", line 7, in <module>
    from .config import *
[0m[0m  File "C:\Users\user\Desktop\FaucetCryptoBot\FaucetCryptoBot\config.py", line 2
[0m[0m    USER_DATA_DIR = C:\Users\user\Desktop\FaucetCryptoBot/data"
[0m[0m                     ^
[0m[0mSyntaxError: invalid syntax
[0m[0m
>>>

**Comment by souravrs999** [comment]
The issue is caused by the path windows might not recognise the forward slash try changing the path to something like below

Example:
`"C:\\Users\\user\\Desktop\\FaucetCryptoBot\\data"
"user-data-dir=C:\\Users\\myusername\\Desktop\\User Data"`

Escape characters should be added to the path string

**Comment by Maro9898** [comment]
ok   
            
          
     
      
       
        Dnia 4 lutego 2021 13:13 Sourav R S &lt;notifications@github.com&gt; napisał(a):
       
    
       
         
 The issue is caused by the path windows might not recognise the forward slash try changing the path to something like below 
 Example:  
 &#34;C:\\Users\\user\\Desktop\\Fau &#34;user-data-dir=C:\\Users\\myus Data&#34; 
 Escape characters should be added to the path string
