### ISSUE TITLE
Always Sleeping 1 min

### ISSUE THREAD

**Issue by rizkyfarhanrr** [souravrs999/FaucetCryptoBot#6]
bro. Initially this went well, but the next day the bot did not want to run normally, it only outputs "sleep 1m" over and over again, I checked the non headless condition also remained the same. even though all ads have not been claimed, is the bot not working now?
thanks bro

**Comment by rizkyfarhanrr** [comment]
do i have to use a proxy?

**Comment by souravrs999** [comment]
Hi @rizkyfarhanrr if the bot is continuously sleeping for 1 min that means it's running into some problem mate. You can fix this by running the bot in non headless mode and check where it's getting stuck usually in login, hope this helps if it did not please feel free to ask again

**Comment by souravrs999** [comment]
> do i have to use a proxy?

Using a proxy is not recommended it will trigger the vpn or proxy detected error

**Comment by souravrs999** [comment]
This issue has been closed due to inactivity.
