### ISSUE TITLE
'NoneType' object has no attribute 'text'

### ISSUE THREAD

**Issue by metapodcod** [souravrs999/FaucetCryptoBot#7]
```
[ 2021-02-17 21:56:02 ] [WARNING] Message: no such element: Unable to locate element: {"method":"xpath","selector":"/html/body/div[1]/div/div/div[1]/div[2]/div/div[2]/span/a"}
  (Session info: chrome=ipadressxxxx)

[ 2021-02-17 21:56:02 ] [WARNING] Message: no such element: Unable to locate element: {"method":"xpath","selector":"/html/body/div[1]/div[2]/main/div/div/div[3]/div[3]/div[1]/div[1]/h3"}
  (Session info: chrome=ipadressxxxx)

[ 2021-02-17 21:56:02 ] [WARNING] 'NoneType' object has no attribute 'text'
[ 2021-02-17 21:56:02 ] [WARNING] Message: no such element: Unable to locate element: {"method":"xpath","selector":"/html/body/div[1]/div[2]/main/div/div/div[3]/div[3]/div[1]/div[1]/h3"}
  (Session info: chrome=ipadressxxxx)

[ 2021-02-17 21:56:02 ] [WARNING] 'NoneType' object has no attribute 'text'
[ 2021-02-17 21:56:02 ] [WARNING] Message: no such element: Unable to locate element: {"method":"xpath","selector":"/html/body/div[1]/div[2]/main/div/div/div[3]/div[3]/div[1]/div[1]/h3"}
  (Session info: chrome=ipadressxxxx)

[ 2021-02-17 21:56:02 ] [WARNING] 'NoneType' object has no attribute 'text'
[ 2021-02-17 21:56:02 ] [WARNING] Message: no such element: Unable to locate element: {"method":"xpath","selector":"/html/body/div[1]/div[2]/main/div/div/div[3]/div[3]/div[1]/div[1]/h3"}
  (Session info: chrome=ipadressxxxx)

[ 2021-02-17 21:56:02 ] [WARNING] 'NoneType' object has no attribute 'text'
[ 2021-02-17 21:56:02 ] [WARNING] Message: no such element: Unable to locate element: {"method":"xpath","selector":"/html/body/div[1]/div[2]/main/div/div/div[3]/div[3]/div[1]/div[1]/h3"}
  (Session info: chrome=ipadressxxxx)

[ 2021-02-17 21:56:02 ] [WARNING] 'NoneType' object has no attribute 'text'
[ 2021-02-17 21:56:02 ] [WARNING] Message: no such element: Unable to locate element: {"method":"xpath","selector":"/html/body/div[1]/div[2]/main/div/div/div[3]/div[3]/div[1]/div[1]/h3"}
  (Session info: chrome=ipadressxxxx)

[ 2021-02-17 21:56:02 ] [WARNING] 'NoneType' object has no attribute 'text'
[ 2021-02-17 21:56:02 ] [WARNING] Message: no such element: Unable to locate element: {"method":"xpath","selector":"/html/body/div[1]/div[2]/main/div/div/div[3]/div[3]/div[1]/div[1]/h3"}
  (Session info: chrome=ipadressxxxx)

[ 2021-02-17 21:56:02 ] [WARNING] 'NoneType' object has no attribute 'text'
[ 2021-02-17 21:56:02 ] [WARNING] Message: no such element: Unable to locate element: {"method":"xpath","selector":"/html/body/div[1]/div[2]/main/div/div/div[3]/div[3]/div[1]/div[1]/h3"}
  (Session info: chrome=ipadressxxxx)

[ 2021-02-17 21:56:02 ] [WARNING] 'NoneType' object has no attribute 'text'
[ 2021-02-17 21:56:02 ] [WARNING] Message: no such element: Unable to locate element: {"method":"xpath","selector":"/html/body/div[1]/div[2]/main/div/div/div[3]/div[3]/div[1]/div[1]/h3"}
  (Session info: chrome=ipadressxxxx)

[ 2021-02-17 21:56:02 ] [WARNING] 'NoneType' object has no attribute 'text'
[ 2021-02-17 21:56:02 ] [WARNING] Message: no such element: Unable to locate element: {"method":"xpath","selector":"/html/body/div[1]/div[2]/main/div/div/div[3]/div[3]/div[1]/div[1]/h3"}
  (Session info: chrome=ipadressxxxx)

[ 2021-02-17 21:56:02 ] [WARNING] 'NoneType' object has no attribute 'text'
[ 2021-02-17 21:56:02 ] [WARNING] Message: no such element: Unable to locate element: {"method":"xpath","selector":"/html/body/div[1]/div[2]/main/div/div/div[3]/div[3]/div[1]/div[1]/h3"}
  (Session info: chrome=ipadressxxxx)

[ 2021-02-17 21:56:02 ] [WARNING] 'NoneType' object has no attribute 'text'
[ 2021-02-17 21:56:02 ] [WARNING] Message: no such element: Unable to locate element: {"method":"xpath","selector":"/html/body/div[1]/div[2]/main/div/div/div[3]/div[3]/div[1]/div[1]/h3"}
  (Session info: chrome=ipadressxxxx)

[ 2021-02-17 21:56:02 ] [WARNING] 'NoneType' object has no attribute 'text'
[ 2021-02-17 21:56:02 ] [WARNING] Message: no such element: Unable to locate element: {"method":"xpath","selector":"/html/body/div[1]/div[2]/main/div/div/div[3]/div[3]/div[1]/div[1]/h3"}
  (Session info: chrome=ipadressxxxx)

[ 2021-02-17 21:56:02 ] [WARNING] 'NoneType' object has no attribute 'text'
[ 2021-02-17 21:56:02 ] [WARNING] Message: no such element: Unable to locate element: {"method":"xpath","selector":"/html/body/div[1]/div[2]/main/div/div/div[3]/div[3]/div[1]/div[1]/h3"}
  (Session info: chrome=ipadressxxxx)

[ 2021-02-17 21:56:02 ] [WARNING] 'NoneType' object has no attribute 'text'
[ 2021-02-17 21:56:02 ] [WARNING] Message: no such element: Unable to locate element: {"method":"xpath","selector":"/html/body/div[1]/div[2]/main/div/div/div[3]/div[3]/div[1]/div[1]/h3"}
  (Session info: chrome=ipadressxxxx)

[ 2021-02-17 21:56:02 ] [WARNING] 'NoneType' object has no attribute 'text'
[ 2021-02-17 21:56:02 ] [WARNING] Message: no such element: Unable to locate element: {"method":"xpath","selector":"/html/body/div[1]/div[2]/main/div/div/div[3]/div[3]/div[1]/div[1]/h3"}
  (Session info: chrome=ipadressxxxx)

[ 2021-02-17 21:56:02 ] [WARNING] 'NoneType' object has no attribute 'text'
[ 2021-02-17 21:56:02 ] [WARNING] Message: no such element: Unable to locate element: {"method":"xpath","selector":"/html/body/div[1]/div[2]/main/div/div/div[3]/div[3]/div[1]/div[1]/h3"}
  (Session info: chrome=ipadressxxxx)

[ 2021-02-17 21:56:02 ] [WARNING] 'NoneType' object has no attribute 'text'
[ 2021-02-17 21:56:02 ] [WARNING] Message: no such element: Unable to locate element: {"method":"xpath","selector":"/html/body/div[1]/div[2]/main/div/div/div[3]/div[3]/div[1]/div[1]/h3"}
  (Session info: chrome=ipadressxxxx)
```

**Comment by metapodcod** [comment]
![Screenshot_2](https://user-images.githubusercontent.com/67564813/108264490-a862e600-7178-11eb-8b22-c73d7c9788ae.jpg)
![Screenshot_1](https://user-images.githubusercontent.com/67564813/108264492-a8fb7c80-7178-11eb-91ee-66cf5c259f05.jpg)

Also, there is an error in the program. If there is no advertisement in the "shortlink ads" section, it automatically goes into sleep mode for 10 minutes, you must do the tasks in order

**Comment by souravrs999** [comment]
> ```
> [ 2021-02-17 21:56:02 ] [WARNING] Message: no such element: Unable to locate element: {"method":"xpath","selector":"/html/body/div[1]/div/div/div[1]/div[2]/div/div[2]/span/a"}
>   (Session info: chrome=ipadressxxxx)
> 
> [ 2021-02-17 21:56:02 ] [WARNING] Message: no such element: Unable to locate element: {"method":"xpath","selector":"/html/body/div[1]/div[2]/main/div/div/div[3]/div[3]/div[1]/div[1]/h3"}
>   (Session info: chrome=ipadressxxxx)
> 
> [ 2021-02-17 21:56:02 ] [WARNING] 'NoneType' object has no attribute 'text'
> [ 2021-02-17 21:56:02 ] [WARNING] Message: no such element: Unable to locate element: {"method":"xpath","selector":"/html/body/div[1]/div[2]/main/div/div/div[3]/div[3]/div[1]/div[1]/h3"}
>   (Session info: chrome=ipadressxxxx)
> 
> [ 2021-02-17 21:56:02 ] [WARNING] 'NoneType' object has no attribute 'text'
> [ 2021-02-17 21:56:02 ] [WARNING] Message: no such element: Unable to locate element: {"method":"xpath","selector":"/html/body/div[1]/div[2]/main/div/div/div[3]/div[3]/div[1]/div[1]/h3"}
>   (Session info: chrome=ipadressxxxx)
> 
> [ 2021-02-17 21:56:02 ] [WARNING] 'NoneType' object has no attribute 'text'
> [ 2021-02-17 21:56:02 ] [WARNING] Message: no such element: Unable to locate element: {"method":"xpath","selector":"/html/body/div[1]/div[2]/main/div/div/div[3]/div[3]/div[1]/div[1]/h3"}
>   (Session info: chrome=ipadressxxxx)
> 
> [ 2021-02-17 21:56:02 ] [WARNING] 'NoneType' object has no attribute 'text'
> [ 2021-02-17 21:56:02 ] [WARNING] Message: no such element: Unable to locate element: {"method":"xpath","selector":"/html/body/div[1]/div[2]/main/div/div/div[3]/div[3]/div[1]/div[1]/h3"}
>   (Session info: chrome=ipadressxxxx)
> 
> [ 2021-02-17 21:56:02 ] [WARNING] 'NoneType' object has no attribute 'text'
> [ 2021-02-17 21:56:02 ] [WARNING] Message: no such element: Unable to locate element: {"method":"xpath","selector":"/html/body/div[1]/div[2]/main/div/div/div[3]/div[3]/div[1]/div[1]/h3"}
>   (Session info: chrome=ipadressxxxx)
> 
> [ 2021-02-17 21:56:02 ] [WARNING] 'NoneType' object has no attribute 'text'
> [ 2021-02-17 21:56:02 ] [WARNING] Message: no such element: Unable to locate element: {"method":"xpath","selector":"/html/body/div[1]/div[2]/main/div/div/div[3]/div[3]/div[1]/div[1]/h3"}
>   (Session info: chrome=ipadressxxxx)
> 
> [ 2021-02-17 21:56:02 ] [WARNING] 'NoneType' object has no attribute 'text'
> [ 2021-02-17 21:56:02 ] [WARNING] Message: no such element: Unable to locate element: {"method":"xpath","selector":"/html/body/div[1]/div[2]/main/div/div/div[3]/div[3]/div[1]/div[1]/h3"}
>   (Session info: chrome=ipadressxxxx)
> 
> [ 2021-02-17 21:56:02 ] [WARNING] 'NoneType' object has no attribute 'text'
> [ 2021-02-17 21:56:02 ] [WARNING] Message: no such element: Unable to locate element: {"method":"xpath","selector":"/html/body/div[1]/div[2]/main/div/div/div[3]/div[3]/div[1]/div[1]/h3"}
>   (Session info: chrome=ipadressxxxx)
> 
> [ 2021-02-17 21:56:02 ] [WARNING] 'NoneType' object has no attribute 'text'
> [ 2021-02-17 21:56:02 ] [WARNING] Message: no such element: Unable to locate element: {"method":"xpath","selector":"/html/body/div[1]/div[2]/main/div/div/div[3]/div[3]/div[1]/div[1]/h3"}
>   (Session info: chrome=ipadressxxxx)
> 
> [ 2021-02-17 21:56:02 ] [WARNING] 'NoneType' object has no attribute 'text'
> [ 2021-02-17 21:56:02 ] [WARNING] Message: no such element: Unable to locate element: {"method":"xpath","selector":"/html/body/div[1]/div[2]/main/div/div/div[3]/div[3]/div[1]/div[1]/h3"}
>   (Session info: chrome=ipadressxxxx)
> 
> [ 2021-02-17 21:56:02 ] [WARNING] 'NoneType' object has no attribute 'text'
> [ 2021-02-17 21:56:02 ] [WARNING] Message: no such element: Unable to locate element: {"method":"xpath","selector":"/html/body/div[1]/div[2]/main/div/div/div[3]/div[3]/div[1]/div[1]/h3"}
>   (Session info: chrome=ipadressxxxx)
> 
> [ 2021-02-17 21:56:02 ] [WARNING] 'NoneType' object has no attribute 'text'
> [ 2021-02-17 21:56:02 ] [WARNING] Message: no such element: Unable to locate element: {"method":"xpath","selector":"/html/body/div[1]/div[2]/main/div/div/div[3]/div[3]/div[1]/div[1]/h3"}
>   (Session info: chrome=ipadressxxxx)
> 
> [ 2021-02-17 21:56:02 ] [WARNING] 'NoneType' object has no attribute 'text'
> [ 2021-02-17 21:56:02 ] [WARNING] Message: no such element: Unable to locate element: {"method":"xpath","selector":"/html/body/div[1]/div[2]/main/div/div/div[3]/div[3]/div[1]/div[1]/h3"}
>   (Session info: chrome=ipadressxxxx)
> 
> [ 2021-02-17 21:56:02 ] [WARNING] 'NoneType' object has no attribute 'text'
> [ 2021-02-17 21:56:02 ] [WARNING] Message: no such element: Unable to locate element: {"method":"xpath","selector":"/html/body/div[1]/div[2]/main/div/div/div[3]/div[3]/div[1]/div[1]/h3"}
>   (Session info: chrome=ipadressxxxx)
> 
> [ 2021-02-17 21:56:02 ] [WARNING] 'NoneType' object has no attribute 'text'
> [ 2021-02-17 21:56:02 ] [WARNING] Message: no such element: Unable to locate element: {"method":"xpath","selector":"/html/body/div[1]/div[2]/main/div/div/div[3]/div[3]/div[1]/div[1]/h3"}
>   (Session info: chrome=ipadressxxxx)
> 
> [ 2021-02-17 21:56:02 ] [WARNING] 'NoneType' object has no attribute 'text'
> [ 2021-02-17 21:56:02 ] [WARNING] Message: no such element: Unable to locate element: {"method":"xpath","selector":"/html/body/div[1]/div[2]/main/div/div/div[3]/div[3]/div[1]/div[1]/h3"}
>   (Session info: chrome=ipadressxxxx)
> 
> [ 2021-02-17 21:56:02 ] [WARNING] 'NoneType' object has no attribute 'text'
> [ 2021-02-17 21:56:02 ] [WARNING] Message: no such element: Unable to locate element: {"method":"xpath","selector":"/html/body/div[1]/div[2]/main/div/div/div[3]/div[3]/div[1]/div[1]/h3"}
>   (Session info: chrome=ipadressxxxx)
> ```

This is normal for the bot and will still continue to run until you run into the continuous waiting for 1 min error

**Comment by souravrs999** [comment]
> ![Screenshot_2](https://user-images.githubusercontent.com/67564813/108264490-a862e600-7178-11eb-8b22-c73d7c9788ae.jpg)
> ![Screenshot_1](https://user-images.githubusercontent.com/67564813/108264492-a8fb7c80-7178-11eb-91ee-66cf5c259f05.jpg)
> 
> Also, there is an error in the program. If there is no advertisement in the "shortlink ads" section, it automatically goes into sleep mode for 10 minutes, you must do the tasks in order

The bot goes through the tasks in the order of main rewards, ptc ads, shortlinks and dosent wait to complete these ads in a single stretch as this trigger s the captcha more often. So it takes a break and tries again after some time, but will finish all the ads nonetheless.

**Comment by metapodcod** [comment]
I ran the bot during the night, slept, woke up still did 1 mission and stayed in the same place 
 some times it pauses for 1 minute #6  your bot did not work as expected doing these operations manually is shorter and risk-free
 
 **Are you sure the bot is working properly ?**

**Comment by souravrs999** [comment]
> I ran the bot during the night, slept, woke up still did 1 mission and stayed in the same place
> some times it pauses for 1 minute #6 your bot did not work as expected doing these operations manually is shorter and risk-free
> 
> **Are you sure the bot is working properly ?**

Yes it is working I have one running continuously and there hasn't been any issues if you are facing the 1 min waits then something's wrong usually you can figure it out by running in normal mode. And find out where it fails also the bot won't complete tasks if faucet crypto returns the vpn or proxy detected error

**Comment by metapodcod** [comment]
> > ![Screenshot_2](https://user-images.githubusercontent.com/67564813/108264490-a862e600-7178-11eb-8b22-c73d7c9788ae.jpg)
> > ![Screenshot_1](https://user-images.githubusercontent.com/67564813/108264492-a8fb7c80-7178-11eb-91ee-66cf5c259f05.jpg)
> > Also, there is an error in the program. If there is no advertisement in the "shortlink ads" section, it automatically goes into sleep mode for 10 minutes, you must do the tasks in order
> 
> The bot goes through the tasks in the order of main rewards, ptc ads, shortlinks and dosent wait to complete these ads in a single stretch as this trigger s the captcha more often. So it takes a break and tries again after some time, but will finish all the ads nonetheless.

what is normal mode?
I use it this way, I do not use vpn or proxy, the bot cannot even log in recently, I have to enter it manually.
```
[Browser]
browser-mode = "headless"
```

**Comment by souravrs999** [comment]
> > > ![Screenshot_2](https://user-images.githubusercontent.com/67564813/108264490-a862e600-7178-11eb-8b22-c73d7c9788ae.jpg)
> > > ![Screenshot_1](https://user-images.githubusercontent.com/67564813/108264492-a8fb7c80-7178-11eb-91ee-66cf5c259f05.jpg)
> > > Also, there is an error in the program. If there is no advertisement in the "shortlink ads" section, it automatically goes into sleep mode for 10 minutes, you must do the tasks in order
> > 
> > 
> > The bot goes through the tasks in the order of main rewards, ptc ads, shortlinks and dosent wait to complete these ads in a single stretch as this trigger s the captcha more often. So it takes a break and tries again after some time, but will finish all the ads nonetheless.
> 
> what is normal mode?
> I use it this way, I do not use vpn or proxy, the bot cannot even log in recently, I have to enter it manually.
> 
> ```
> [Browser]
> browser-mode = "headless"
> ```

Removing the headless flag will start the driver in normal mode and you will be able to see the driver doing its job and you can pinpoint the issue if you are sure that the bot is not able to login then that might be caused by captcha. But I highly doubt it since a cookie will be created at the first login and the bot will further login by loading this file.

**Comment by metapodcod** [comment]
the program works the same in both cases, but nothing changes, In both cases the browser opens, I couldn't understand how it works, but all the output already appears in the terminal. 

I found a bug in the current version Although there is no task, it still tries to click and perform tasks, which is a good reason to be banned 👎

Can you add a way to work with multiple accounts ?

**Comment by souravrs999** [comment]
> the program works the same in both cases, but nothing changes, In both cases the browser opens, I couldn't understand how it works, but all the output already appears in the terminal.
> 
> I found a bug in the current version Although there is no task, it still tries to click and perform tasks, which is a good reason to be banned 👎
> 
> Can you add a way to work with multiple accounts ?

Ok multiple things to unpack here Nonetype error basically means the webdiver was unable to find the web element we are looking for if you can wait the newer version gives much better error codes which is under testing but might com out in the following days. 

About the bug part it isn't actually a bug with the bot the bot has to check for available tasks within their respective pages since Faucet Cryptos counter on the dashboard is bugged so there is no other way to check for task, this necessarily won't get you banned but the following will
User Agent, Headers, Unobfuscated webdriver, request methods etc.. (Faucet Crypto currently dosent check for those but might change in the future)

I can't actually add anyway to work with multiple accounts in a single web instance, at that point you are basically begging for a ban but since it's written like a class you can write your own logic for it or create a copy of the bot with the new account credentials and private proxy.

**Comment by souravrs999** [comment]
> the program works the same in both cases, but nothing changes, In both cases the browser opens, I couldn't understand how it works, but all the output already appears in the terminal.
> 
> I found a bug in the current version Although there is no task, it still tries to click and perform tasks, which is a good reason to be banned 👎
> 
> Can you add a way to work with multiple accounts ?

Hoping you have updated the xpaths faucet crypos website was changed recently

**Comment by souravrs999** [comment]
This issue has been closed due to inactivity.

**Comment by metapodcod** [comment]
![image](https://user-images.githubusercontent.com/67564813/108639568-55559f80-74a6-11eb-889a-f1e69c44bdc0.png)
Can't it be done by checking the numbers here? If there is no number here, the transaction cannot be done

**Comment by souravrs999** [comment]
> ![image](https://user-images.githubusercontent.com/67564813/108639568-55559f80-74a6-11eb-889a-f1e69c44bdc0.png)
> Can't it be done by checking the numbers here? If there is no number here, the transaction cannot be done @souravrs999

That was how it was done before the update but those are bugged and dosent show the number of tasks properly we can resort to that if the website gets fixed

**Comment by metapodcod** [comment]
```
r 14 sec
[ 2021-02-28 01:45:42 ] [WARNING] Message: no such element: Unable to locate element: {"method":"xpath","selector":"/html/body/div[1]/div[2]/main/div/div/div[3]/div[6]/span[2]/button"}
  (Session info: chrome=ipadressxxxx)

[ 2021-02-28 01:45:42 ] [WARNING] Message: no such element: Unable to locate element: {"method":"xpath","selector":"/html/body/div[1]/div[2]/main/div/div/div[3]/div[3]/div[1]/div[1]/h3"}
  (Session info: chrome=ipadressxxxx)

[ 2021-02-28 01:45:42 ] [WARNING] 'NoneType' object has no attribute 'text'
[ 2021-02-28 01:45:42 ] [WARNING] Message: no such element: Unable to locate element: {"method":"xpath","selector":"/html/body/div[1]/div[2]/main/div/div/div[3]/div[3]/div[1]/div[1]/h3"}
  (Session info: chrome=ipadressxxxx)

[ 2021-02-28 01:45:42 ] [WARNING] 'NoneType' object has no attribute 'text'
[ 2021-02-28 01:45:42 ] [WARNING] Message: no such element: Unable to locate element: {"method":"xpath","selector":"/html/body/div[1]/div[2]/main/div/div/div[3]/div[3]/div[1]/div[1]/h3"}
  (Session info: chrome=ipadressxxxx)

[ 2021-02-28 01:45:42 ] [WARNING] 'NoneType' object has no attribute 'text'
[ 2021-02-28 01:45:42 ] [WARNING] Message: no such element: Unable to locate element: {"method":"xpath","selector":"/html/body/div[1]/div[2]/main/div/div/div[3]/div[3]/div[1]/div[1]/h3"}
  (Session info: chrome=ipadressxxxx)

[ 2021-02-28 01:45:42 ] [WARNING] 'NoneType' object has no attribute 'text'
[ 2021-02-28 01:45:42 ] [WARNING] Message: no such element: Unable to locate element: {"method":"xpath","selector":"/html/body/div[1]/div[2]/main/div/div/div[3]/div[3]/div[1]/div[1]/h3"}
  (Session info: chrome=ipadressxxxx)

[ 2021-02-28 01:45:42 ] [WARNING] 'NoneType' object has no attribute 'text'
[ 2021-02-28 01:45:42 ] [WARNING] Message: no such element: Unable to locate element: {"method":"xpath","selector":"/html/body/div[1]/div[2]/main/div/div/div[3]/div[3]/div[1]/div[1]/h3"}
  (Session info: chrome=ipadressxxxx)

[ 2021-02-28 01:45:42 ] [WARNING] 'NoneType' object has no attribute 'text'
[ 2021-02-28 01:45:42 ] [WARNING] Message: no such element: Unable to locate element: {"method":"xpath","selector":"/html/body/div[1]/div[2]/main/div/div/div[3]/div[3]/div[1]/div[1]/h3"}
  (Session info: chrome=ipadressxxxx)

[ 2021-02-28 01:45:42 ] [WARNING] 'NoneType' object has no attribute 'text'
[ 2021-02-28 01:45:42 ] [WARNING] Message: no such element: Unable to locate element: {"method":"xpath","selector":"/html/body/div[1]/div[2]/main/div/div/div[3]/div[3]/div[1]/div[1]/h3"}
  (Session info: chrome=ipadressxxxx)

[ 2021-02-28 01:45:42 ] [WARNING] 'NoneType' object has no attribute 'text'
[ 2021-02-28 01:45:42 ] [WARNING] Message: no such element: Unable to locate element: {"method":"xpath","selector":"/html/body/div[1]/div[2]/main/div/div/div[3]/div[3]/div[1]/div[1]/h3"}
  (Session info: chrome=ipadressxxxx)

[ 2021-02-28 01:45:42 ] [WARNING] 'NoneType' object has no attribute 'text'
[ 2021-02-28 01:45:42 ] [WARNING] Message: no such element: Unable to locate element: {"method":"xpath","selector":"/html/body/div[1]/div[2]/main/div/div/div[3]/div[3]/div[1]/div[1]/h3"}
  (Session info: chrome=ipadressxxxx)

[ 2021-02-28 01:45:42 ] [WARNING] 'NoneType' object has no attribute 'text'
[ 2021-02-28 01:45:42 ] [WARNING] Message: no such element: Unable to locate element: {"method":"xpath","selector":"/html/body/div[1]/div[2]/main/div/div/div[3]/div[3]/div[1]/div[1]/h3"}
  (Session info: chrome=ipadressxxxx)

[ 2021-02-28 01:45:42 ] [WARNING] 'NoneType' object has no attribute 'text'
[ 2021-02-28 01:45:42 ] [WARNING] Message: no such element: Unable to locate element: {"method":"xpath","selector":"/html/body/div[1]/div[2]/main/div/div/div[3]/div[3]/div[1]/div[1]/h3"}
  (Session info: chrome=ipadressxxxx)

[ 2021-02-28 01:45:42 ] [WARNING] 'NoneType' object has no attribute 'text'
[ 2021-02-28 01:45:42 ] [WARNING] Message: no such element: Unable to locate element: {"method":"xpath","selector":"/html/body/div[1]/div[2]/main/div/div/div[3]/div[3]/div[1]/div[1]/h3"}
  (Session info: chrome=ipadressxxxx)

[ 2021-02-28 01:45:42 ] [WARNING] 'NoneType' object has no attribute 'text'
[ 2021-02-28 01:45:42 ] [WARNING] Message: no such element: Unable to locate element: {"method":"xpath","selector":"/html/body/div[1]/div[2]/main/div/div/div[3]/div[3]/div[1]/div[1]/h3"}
  (Session info: chrome=ipadressxxxx)

[ 2021-02-28 01:45:42 ] [WARNING] 'NoneType' object has no attribute 'text'
[ 2021-02-28 01:45:42 ] [WARNING] Message: no such element: Unable to locate element: {"method":"xpath","selector":"/html/body/div[1]/div[2]/main/div/div/div[3]/div[3]/div[1]/div[1]/h3"}
  (Session info: chrome=ipadressxxxx)

[ 2021-02-28 01:45:42 ] [WARNING] 'NoneType' object has no attribute 'text'
[ 2021-02-28 01:45:42 ] [WARNING] Message: no such element: Unable to locate element: {"method":"xpath","selector":"/html/body/div[1]/div[2]/main/div/div/div[3]/div[3]/div[1]/div[1]/h3"}
  (Session info: chrome=ipadressxxxx)

[ 2021-02-28 01:45:42 ] [WARNING] 'NoneType' object has no attribute 'text'
[ 2021-02-28 01:45:42 ] [WARNING] Message: no such element: Unable to locate element: {"method":"xpath","selector":"/html/body/div[1]/div[2]/main/div/div/div[3]/div[3]/div[1]/div[1]/h3"}
  (Session info: chrome=ipadressxxxx)

[ 2021-02-28 01:45:42 ] [WARNING] 'NoneType' object has no attribute 'text'
[ 2021-02-28 01:45:42 ] [WARNING] Message: no such element: Unable to locate element: {"method":"xpath","selector":"/html/body/div[1]/div[2]/main/div/div/div[3]/div[3]/div[1]/div[1]/h3"}
  (Session info: chrome=ipadressxxxx)

[ 2021-02-28 01:45:42 ] [WARNING] 'NoneType' object has no attribute 'text'
[ 2021-02-28 01:45:42 ] [WARNING] Message: no such element: Unable to locate element: {"method":"xpath","selector":"/html/body/div[1]/div[2]/main/div/div/div[3]/div[3]/div[1]/div[1]/h3"}
  (Session info: chrome=ipadressxxxx)

[ 2021-02-28 01:45:42 ] [WARNING] 'NoneType' object has no attribute 'text'
[ 2021-02-28 01:45:42 ] [WARNING] Message: no such element: Unable to locate element: {"method":"xpath","selector":"/html/body/div[1]/div[2]/main/div/div/div[3]/div[3]/div[1]/div[1]/h3"}
  (Session info: chrome=ipadressxxxx)

[ 2021-02-28 01:45:42 ] [WARNING] 'NoneType' object has no attribute 'text'
[ 2021-02-28 01:45:42 ] [  BOT  ] SHORTLINK ADS
[ 2021-02-28 01:45:44 ] [  BOT  ] Waiting for 3 sec
[ 2021-02-28 01:45:47 ] [  BOT  ] Total shortlinks: 5
[ 2021-02-28 01:45:47 ] [  BOT  ] Completed shortlinks: 3
[ 2021-02-28 01:45:47 ] [  BOT  ] Available shortlinks: 20
[ 2021-02-28 01:45:47 ] [  BOT  ] Total earnable coins: 282.60
[ 2021-02-28 01:45:47 ] [  BOT  ] SH.FAUCETCRYPTO.COM
[ 2021-02-28 01:45:47 ] [  BOT  ] View count: sh.faucetcrypto.com [6/7 Views]
[ 2021-02-28 01:45:47 ] [  BOT  ] Reward coins: sh.faucetcrypto.com [14.13 Coins]
[ 2021-02-28 01:45:47 ] [  BOT  ] Waiting for 16 sec
[ 2021-02-28 01:46:03 ] [WARNING] Message: no such element: Unable to locate element: {"method":"xpath","selector":"/html/body/div[1]/div[2]/main/div/div/div[3]/div[6]/span[2]/button"}
  (Session info: chrome=ipadressxxxx)

[ 2021-02-28 01:46:03 ] [WARNING] Message: no such element: Unable to locate element: {"method":"xpath","selector":"/html/body/div[1]/div[2]/main/div/div/div[3]/div[5]/div[4]/div[2]/div[1]/div/div[1]/div"}
  (Session info: chrome=ipadressxxxx)

[ 2021-02-28 01:46:03 ] [WARNING] 'NoneType' object has no attribute 'text'
[ 2021-02-28 01:46:03 ] [WARNING] Message: no such element: Unable to locate element: {"method":"xpath","selector":"/html/body/div[1]/div[2]/main/div/div/div[3]/div[5]/div[5]/div[2]/div[1]/div/div[1]/div"}
  (Session info: chrome=ipadressxxxx)

[ 2021-02-28 01:46:03 ] [WARNING] 'NoneType' object has no attribute 'text'
```

**Comment by metapodcod** [comment]
@souravrs999 where exactly is this I tried these but it didn't work

`"ptc-ads-title": "/html/body/div[1]/div[2]/main/div/div/div[3]/div[3]/div[1]/div[1]/h3",`  
![image](https://user-images.githubusercontent.com/67564813/110306789-4545d000-800f-11eb-9baf-2090ca15f7a5.png)
![image](https://user-images.githubusercontent.com/67564813/110306825-5098fb80-800f-11eb-9e90-33c7595ddb42.png)
