### ISSUE TITLE
Not picking up Main Reward

### ISSUE THREAD

**Issue by DogeBotDoge** [souravrs999/FaucetCryptoBot#8]
when trying to collect the main reward the following error is displayed..

[  BOT  ] MAIN REWARD
[SUCCESS] Main reward is available
[  BOT  ] Waiting for 3 sec
[WARNING] Message: no such element: Unable to locate element: {"method":"xpath","selector":"/html/body/div[1]/div[2]/main/div/div/div[3]/div[3]/div/div/p"}
 
The xpath for this must have changed..

**Comment by souravrs999** [comment]
The layout of Faucet Crypto has changed and the bot won't work anymore you can wait for me to release the updated xpath file or you can add them manually to the xpath.py file.

**Comment by souravrs999** [comment]
> when trying to collect the main reward the following error is displayed..
> 
> [ BOT ] MAIN REWARD
> [SUCCESS] Main reward is available
> [ BOT ] Waiting for 3 sec
> [WARNING] Message: no such element: Unable to locate element: {"method":"xpath","selector":"/html/body/div[1]/div[2]/main/div/div/div[3]/div[3]/div/div/p"}
> 
> The xpath for this must have changed..

The xpaths have been fixed please try again do let me know if i've missed something.
